version: '3.9'

services:
  builder:
    container_name: joomlagov_builder
    restart: always
    build:
      context: .
      dockerfile: ./.docker/node/Dockerfile
    ports:
      - '3000:3000'
      - '3001:3001'
    volumes:
      - .:/usr/src/joomlagov
    command: gulp default --host web

  web:
    container_name: joomlagov_web
    restart: always
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    container_name: joomlagov_db
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: brasil
