version: '3.9'

services:
  web:
    container_name: joomlagov_web
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./.docker/nginx:/etc/nginx/templates
      - web-data:/var/www/html
    environment:
      NGINX_HOST: localhost
    links:
      - php

  php:
    container_name: joomlagov_php
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - web-data:/var/www/html
    links:
      - db

  db:
    container_name: joomlagov_db
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: brasil

volumes:
  web-data:
