version: "3.9"

services:
  builder:
    container_name: joomlagov_builder
    build:
      context: .
      dockerfile: Dockerfile-node
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - .:/usr/src/joomlagov
    command: gulp default --host web

  web:
    container_name: joomlagov_web
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
